language: php

notifications:
  email: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - 'nightly'

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis_retry composer require codeception/codeception:${CODECEPTION_VERSION}

script:
  - vendor/bin/codecept run
