name: CI

on: push

jobs:
  php56:
    name: Test on PHP 5.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MilesChou/composer-action/5.6/install@master
      - uses: docker://php:5.6-alpine
        with:
          args: vendor/bin/codecept run
