name: CI

on: push

strategy:
  matrix:
    php: [5.6, 7.0, 7.1, 7.2, 7.3]

jobs:
  codeception:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MilesChou/composer-action/${{ matrix.php }}/install@master
      - uses: docker://php:${{ matrix.php }}-alpine
        with:
          args: vendor/bin/codecept run
