name: CI

on: push

jobs:
  build:
    name: Test on PHP 5.6
    runs-on: ubuntu-18.04
    steps:
      - name: Composer install
        uses: MilesChou/composer-action/5.6/install@master
        with:
          args: install
      - name: Codeception testing
        uses: docker://php:5.6
        with:
          args: vendor/bin/codecept/run
