name: CI

on: push

jobs:
  build:
    name: Test on PHP 5.6
    runs-on: ubuntu-18.04
    steps:
      - name: composer update
        uses: MilesChou/composer-action/5.6/@master
        with:
          args: update
      - name: composer run test
        uses: MilesChou/composer-action/5.6/@master
        with:
          args: run test
